declare const styles: {
  readonly statePage: string;
  readonly errorPage: string;
  readonly stateHeader: string;
  readonly headerOverlay: string;
  readonly headerContent: string;
  readonly heroStats: string;
  readonly statBadge: string;
  readonly holidayContent: string;
  readonly familyActivities: string;
  readonly plannerPromo: string;
  readonly promoContent: string;
  readonly promoStats: string;
  readonly promoStat: string;
  readonly promoValue: string;
  readonly promoLabel: string;
  readonly promoText: string;
  readonly promoFeatures: string;
  readonly promoFeature: string;
  readonly promoIcon: string;
  readonly promoCTA: string;
  readonly promoArrow: string;
  readonly seasonCard: string;
  readonly spring: string;
  readonly summer: string;
  readonly autumn: string;
  readonly winter: string;
  [key: string]: string;
};

export default styles; 